version: '3.8'

services:
  db:
    image: postgres:15
    container_name: odoo19_db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo19
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  odoo:
    build: .
    container_name: odoo19_app
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONPYCACHEPREFIX: /tmp/pycache
    volumes:
      - odoo_data:/var/lib/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - ./asset_management:/mnt/extra-addons/asset_management
      - ./ica_web_responsive:/mnt/extra-addons/ica_web_responsive
    restart: unless-stopped

volumes:
  pgdata:
  odoo_data: