[options]
admin_passwd = admin123

; PostgreSQL connection
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = odoo19

; 🔥 IMPORTANT: Allow multiple databases
dbfilter = .*
list_db = True

; Addons
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

; Performance
log_level = info
workers = 2
limit_time_real = 600
limit_time_cpu = 300